#!/usr/bin/env bash
set -euo pipefail

ROOT="${MINERU_VLM_LAB_ROOT:-/data/mineru-vlm-lab}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck disable=SC1091
source "$SCRIPT_DIR/env_helpers.sh"
load_env_preserving_overrides "$ROOT/production.env" \
  MINERU_ENV \
  MINERU_VLM_LAB_PORT \
  MINERU_ORCHESTRATOR_DRY_RUN \
  MINERU_VLM_LAB_WORK_ROOT \
  MINERU_VLM_BASE_URL \
  MAX_CONCURRENT_VLM_PAGES \
  EMBEDDING_PROVIDER \
  EMBEDDING_MODEL_PATH \
  EMBEDDING_MODEL \
  EMBEDDING_DIM \
  EMBEDDING_DEVICE \
  EMBEDDING_MAX_LENGTH \
  EMBEDDING_BATCH_SIZE \
  MAX_CONCURRENT_EMBEDDING_BATCHES \
  PRELOAD_EMBEDDING \
  NATIVE_TABLE_EXTRACTION_MODE \
  DEFERRED_TABLE_QUEUE_MODE \
  DEFERRED_TABLE_MIN_COMPLEX_BLOCKS \
  DEFERRED_TABLE_MIN_COMPLEX_CHARS \
  ENHANCEMENT_TABLE_MAX_IMAGE_WIDTH \
  ENHANCEMENT_COMPLEX_TABLE_MAX_IMAGE_WIDTH \
  ENHANCEMENT_COMPLEX_TABLE_MIN_ROWS \
  ENHANCEMENT_COMPLEX_TABLE_MIN_COLUMNS \
  ENHANCEMENT_COMPLEX_TABLE_MIN_CHARS \
  ENHANCEMENT_COMPLEX_TABLE_MIN_LINES \
  ENHANCEMENT_COMPLEX_TABLE_MIN_AREA

MINERU_ENV="${MINERU_ENV:-/data/mineru32-bench/env}"
PORT="${MINERU_VLM_LAB_PORT:-18180}"
DRY_RUN="${MINERU_ORCHESTRATOR_DRY_RUN:-0}"

EMBEDDING_PROVIDER_OVERRIDE="${EMBEDDING_PROVIDER:-}"
EMBEDDING_MODEL_PATH_OVERRIDE="${EMBEDDING_MODEL_PATH:-}"
EMBEDDING_MODEL_OVERRIDE="${EMBEDDING_MODEL:-}"
EMBEDDING_DIM_OVERRIDE="${EMBEDDING_DIM:-}"
EMBEDDING_DEVICE_OVERRIDE="${EMBEDDING_DEVICE:-}"
EMBEDDING_MAX_LENGTH_OVERRIDE="${EMBEDDING_MAX_LENGTH:-}"
EMBEDDING_BATCH_SIZE_OVERRIDE="${EMBEDDING_BATCH_SIZE:-}"
MAX_CONCURRENT_EMBEDDING_BATCHES_OVERRIDE="${MAX_CONCURRENT_EMBEDDING_BATCHES:-}"
PRELOAD_EMBEDDING_OVERRIDE="${PRELOAD_EMBEDDING:-}"

export MINERU_VLM_LAB_ROOT="$ROOT"
export MINERU_VLM_LAB_WORK_ROOT="${MINERU_VLM_LAB_WORK_ROOT:-$ROOT/work}"
export MINERU_VLM_BASE_URL="${MINERU_VLM_BASE_URL:-http://127.0.0.1:18100}"
export MAX_CONCURRENT_VLM_PAGES="${MAX_CONCURRENT_VLM_PAGES:-2}"
if [ -f "$ROOT/embedding.env" ]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/embedding.env"
  set +a
fi

if [ -n "$EMBEDDING_PROVIDER_OVERRIDE" ]; then export EMBEDDING_PROVIDER="$EMBEDDING_PROVIDER_OVERRIDE"; fi
if [ -n "$EMBEDDING_MODEL_PATH_OVERRIDE" ]; then export EMBEDDING_MODEL_PATH="$EMBEDDING_MODEL_PATH_OVERRIDE"; fi
if [ -n "$EMBEDDING_MODEL_OVERRIDE" ]; then export EMBEDDING_MODEL="$EMBEDDING_MODEL_OVERRIDE"; fi
if [ -n "$EMBEDDING_DIM_OVERRIDE" ]; then export EMBEDDING_DIM="$EMBEDDING_DIM_OVERRIDE"; fi
if [ -n "$EMBEDDING_DEVICE_OVERRIDE" ]; then export EMBEDDING_DEVICE="$EMBEDDING_DEVICE_OVERRIDE"; fi
if [ -n "$EMBEDDING_MAX_LENGTH_OVERRIDE" ]; then export EMBEDDING_MAX_LENGTH="$EMBEDDING_MAX_LENGTH_OVERRIDE"; fi
if [ -n "$EMBEDDING_BATCH_SIZE_OVERRIDE" ]; then export EMBEDDING_BATCH_SIZE="$EMBEDDING_BATCH_SIZE_OVERRIDE"; fi
if [ -n "$MAX_CONCURRENT_EMBEDDING_BATCHES_OVERRIDE" ]; then export MAX_CONCURRENT_EMBEDDING_BATCHES="$MAX_CONCURRENT_EMBEDDING_BATCHES_OVERRIDE"; fi
if [ -n "$PRELOAD_EMBEDDING_OVERRIDE" ]; then export PRELOAD_EMBEDDING="$PRELOAD_EMBEDDING_OVERRIDE"; fi

export EMBEDDING_PROVIDER="${EMBEDDING_PROVIDER:-hash}"
export EMBEDDING_DIM="${EMBEDDING_DIM:-32}"
export EMBEDDING_BATCH_SIZE="${EMBEDDING_BATCH_SIZE:-64}"
export MAX_CONCURRENT_EMBEDDING_BATCHES="${MAX_CONCURRENT_EMBEDDING_BATCHES:-2}"
mkdir -p "$ROOT/work" "$ROOT/logs"

args=("$MINERU_ENV/bin/uvicorn" app.main:app --host 0.0.0.0 --port "$PORT" --app-dir "$ROOT")

if [[ "$DRY_RUN" =~ ^(1|true|yes|on)$ ]]; then
  for name in \
    MINERU_VLM_BASE_URL \
    EMBEDDING_PROVIDER \
    EMBEDDING_MODEL_PATH \
    EMBEDDING_MODEL \
    EMBEDDING_DIM \
    EMBEDDING_DEVICE \
    EMBEDDING_MAX_LENGTH \
    EMBEDDING_BATCH_SIZE \
    MAX_CONCURRENT_EMBEDDING_BATCHES \
    PRELOAD_EMBEDDING \
    NATIVE_TABLE_EXTRACTION_MODE \
    DEFERRED_TABLE_QUEUE_MODE \
    DEFERRED_TABLE_MIN_COMPLEX_BLOCKS \
    DEFERRED_TABLE_MIN_COMPLEX_CHARS \
    ENHANCEMENT_TABLE_MAX_IMAGE_WIDTH \
    ENHANCEMENT_COMPLEX_TABLE_MAX_IMAGE_WIDTH; do
    if [ -n "${!name:-}" ]; then
      printf 'ENV %s=%s\n' "$name" "${!name}"
    fi
  done
  printf 'CMD'
  for arg in "${args[@]}"; do
    printf ' %q' "$arg"
  done
  printf '\n'
  exit 0
fi

source "$MINERU_ENV/bin/activate"
exec "${args[@]}"
